FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los scripts a la imagen
COPY app/requirements.txt /app/requirements.txt
COPY app /app

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto
EXPOSE 5000

# Ejecutar la aplicación Flask
CMD ["python", "app.py"]

